### ISSUE TITLE
Don`t Worked To Me

### ISSUE THREAD

**Issue by Case-Ox** [BaR1BoD/MCreator-Dyeable#1]
MCreator doesn`t recognise your code when building in my project:
And mixin did not recognised your elements

Executing Gradle task: build 
Build info: MCreator 2024.2.29712, forge-1.20.1, 64-bit, 8105 MB, Windows 11, JVM 21.0.3, JAVA_HOME: C:\Users\PC\Downloads\MCreator.2024.2.Windows.64bit\MCreator20242\jdk, started on: 2024-07-27-22:43:34 
Loaded APIs: jei 
 
> Configure project : 
MixinGradle did not locate the diffplug APT plugin, skipping eclipse task configuration 
> Task :downloadMcpConfig 
> Task :extractSrg UP-TO-DATE 
> Task :createMcpToSrg UP-TO-DATE 
> Task :compileJava 
Note: SpongePowered MIXIN Annotation Processor Version=0.8.5 (MixinGradle Version=0.7.38) 
Note: Supported obfuscation types: ObfuscationServiceMCP supports [notch] ObfuscationServiceFG3 supports [searge] 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\ExtendedCraftMod.java:44](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/ExtendedCraftMod.java:44): error: cannot find symbol 
        bus.addListener(RegisterColor::onItemColorRegister); 
                        ^ 
  symbol:   variable RegisterColor 
  location: class ExtendedCraftMod 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\init\ExtendedCraftModItems.java:17](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/init/ExtendedCraftModItems.java:17): error: cannot find symbol 
    public static final RegistryObject<Item> LINGERING_ARROW = REGISTRY.register("lingering_arrow", () -> new LingeringArrowItem()); 
                                                                                                              ^ 
  symbol:   class LingeringArrowItem 
  location: class ExtendedCraftModItems 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:13](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:13): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:16](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:16): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:19](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:19): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:22](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:22): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:25](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:25): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:28](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:28): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:31](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:31): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:34](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:34): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:37](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:37): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:40](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:40): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:43](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:43): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:46](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:46): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:49](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:49): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:52](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:52): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:55](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:55): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:58](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:58): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
[C:\Users\PC\MCreatorWorkspaces\extended_craft\src\main\java\net\mcreator\extendedcraft\procedures\LingeringArrowPropertyValueProviderProcedure.java:61](file:///C:/Users/PC/MCreatorWorkspaces/extended_craft/src/main/java/net/mcreator/extendedcraft/procedures/LingeringArrowPropertyValueProviderProcedure.java:61): error: incompatible types: ItemStack cannot be converted to IDyeableItem 
            if (itemstack instanceof IDyeableItem _dyeableItem_) 
                ^ 
19 errors 
> Task :compileJava FAILED 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --info option to get more log output. 
> Run with --scan to get full insights. 
BUILD FAILED in 1m 37s 
4 actionable tasks: 2 executed, 2 up-to-date 
 
BUILD FAILED 
Task completed in 1 minute and 44 seconds

**Comment by BaR1BoD** [comment]
fixed
